version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ordersapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x7acfukc09z5"
s3_prefix = "ordersapi"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
